### ISSUE TITLE
[Test] Fix directTransferForm tests

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1478]
```
FAIL  src/tests/e2e/directTransferForm.test.e2e.js (190.405s)
  Direct transfer form tests
    ✓ Transfer in/out switch (4725ms)
    ✓ Transfer ETH into Drive (8434ms)
    ✕ Transfer DAI into Drive (64742ms)
    ✓ Transfer BTC into Drive (10766ms)
    ✓ Transfer BTC from Drive (11918ms)
    ✓ Transfer DAI from Drive (10398ms)
    ✕ Transfer ETH from Drive (64499ms)
    ✓ Back Btn (5839ms)

  ● Direct transfer form tests › Transfer DAI into Drive

    TimeoutError: Navigation timeout of 30000 ms exceeded

      24 | 
      25 |   beforeEach(async () => {
    > 26 |     await Promise.all([
         |     ^
      27 |       page.waitForNavigation({
      28 |         waitUntil: 'networkidle0'
      29 |       }),

      at ../../../node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
      at FrameManager.waitForFrameNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:139:19)
      at Frame.waitForNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:414:12)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:12)
          at async Promise.all (index 0)
      at Object.<anonymous> (directTransferForm.test.e2e.js:26:5)
        -- ASYNC --
      at Frame.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:49)
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:112:23)
      at Object.waitForNavigation (directTransferForm.test.e2e.js:27:12)
          at runMicrotasks (<anonymous>)
        -- ASYNC --
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Object.waitForNavigation (directTransferForm.test.e2e.js:27:12)
          at runMicrotasks (<anonymous>)

  ● Direct transfer form tests › Transfer DAI into Drive

    TimeoutError: Navigation timeout of 30000 ms exceeded

      4 |   async dispatchFormActions (action) {
      5 |     if (action === 'continue') {
    > 6 |       await Promise.all([
        |       ^
      7 |         page.click('[data-test-id="continue"]'),
      8 |         page.waitForNavigation({
      9 |           waitUntil: 'networkidle0'

      at ../../../node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
      at FrameManager.waitForFrameNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:139:19)
      at Frame.waitForNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:414:12)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:12)
          at async Promise.all (index 1)
      at DirectTransferFormPage.dispatchFormActions (pages/directTransferForm.page.js:6:7)
      at Object.<anonymous> (directTransferForm.test.e2e.js:139:7)
        -- ASYNC --
      at Frame.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:49)
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:112:23)
      at DirectTransferFormPage.waitForNavigation [as dispatchFormActions] (pages/directTransferForm.page.js:8:14)
      at Object.dispatchFormActions (directTransferForm.test.e2e.js:139:21)
          at runMicrotasks (<anonymous>)

  ● Direct transfer form tests › Transfer ETH from Drive

    TimeoutError: Navigation timeout of 30000 ms exceeded

      24 | 
      25 |   beforeEach(async () => {
    > 26 |     await Promise.all([
         |     ^
      27 |       page.waitForNavigation({
      28 |         waitUntil: 'networkidle0'
      29 |       }),

      at ../../../node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
      at FrameManager.waitForFrameNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:139:19)
      at Frame.waitForNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:414:12)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:12)
          at async Promise.all (index 0)
      at Object.<anonymous> (directTransferForm.test.e2e.js:26:5)
        -- ASYNC --
      at Frame.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:49)
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:112:23)
      at Object.waitForNavigation (directTransferForm.test.e2e.js:27:12)
          at runMicrotasks (<anonymous>)
        -- ASYNC --
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Object.waitForNavigation (directTransferForm.test.e2e.js:27:12)
          at runMicrotasks (<anonymous>)

  ● Direct transfer form tests › Transfer ETH from Drive

    TimeoutError: Navigation timeout of 30000 ms exceeded

      4 |   async dispatchFormActions (action) {
      5 |     if (action === 'continue') {
    > 6 |       await Promise.all([
        |       ^
      7 |         page.click('[data-test-id="continue"]'),
      8 |         page.waitForNavigation({
      9 |           waitUntil: 'networkidle0'

      at ../../../node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
      at FrameManager.waitForFrameNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:139:19)
      at Frame.waitForNavigation (../../../node_modules/puppeteer/lib/FrameManager.js:414:12)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:12)
          at async Promise.all (index 1)
      at DirectTransferFormPage.dispatchFormActions (pages/directTransferForm.page.js:6:7)
      at Object.<anonymous> (directTransferForm.test.e2e.js:312:7)
        -- ASYNC --
      at Frame.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:111:15)
      at Page.waitForNavigation (../../../node_modules/puppeteer/lib/Page.js:692:49)
      at Page.<anonymous> (../../../node_modules/puppeteer/lib/helper.js:112:23)
      at DirectTransferFormPage.waitForNavigation [as dispatchFormActions] (pages/directTransferForm.page.js:8:14)
      at Object.dispatchFormActions (directTransferForm.test.e2e.js:312:21)
          at runMicrotasks (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 6 passed, 8 total
Snapshots:   0 total
Time:        190.443s
```

**Comment by timothywangdev** [comment]
```
 waitUntil: 'networkidle0'
```

causing hangs, not sure why it does not work
